FROM ubuntu:latest
ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/time
RUN apt-get update && apt-get upgrade -y && apt-get autoremove -y
RUN apt-get install curl wget  -yq
RUN curl -sL https://deb.nodesource.com/setup_15.x | bash -
RUN apt-get install -y nodejs
RUN apt-get install net-tools iputils-ping -yq

# install dapr cli
RUN echo
RUN wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
RUN dapr init --slim

# install daprd
ENV PATH="/root/.dapr/bin/:${PATH}"

# install app
WORKDIR /app
COPY . .
RUN npm install
EXPOSE 3000
EXPOSE 3500
EXPOSE 50002
ENTRYPOINT ["/app/startup.sh"]
